#!/usr/bin/env bash
# Scaffold secrets.env from secrets.env.example and auto-generate the random
# secrets. Idempotent: never overwrites a value that is already set.
set -euo pipefail

EXAMPLE="secrets.env.example"
OUT="secrets.env"

[ -f "$EXAMPLE" ] || { echo "error: $EXAMPLE not found (run from repo root)" >&2; exit 1; }

# Seed secrets.env from the example on first run.
if [ ! -f "$OUT" ]; then
  cp "$EXAMPLE" "$OUT"
fi
chmod 600 "$OUT"

# Reconcile: append any KEY= lines present in the example but missing from
# secrets.env (verbatim, so example defaults like LITELLM_UI_USERNAME=admin
# carry over). Lets a newly-added secret be picked up on an existing file.
while IFS= read -r line; do
  case "$line" in
    [A-Z_]*=*)
      key="${line%%=*}"
      grep -q "^${key}=" "$OUT" || printf '%s\n' "$line" >> "$OUT"
      ;;
  esac
done < "$EXAMPLE"

rand_alnum() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom 2>/dev/null | head -c "${1:-28}" || true; }

# Set KEY only if currently blank ("KEY=" with nothing after). Idempotent.
# Uses a literal read/printf rewrite (no sed) so values may contain | & \ etc.
set_if_blank() {
  local key="$1" value="$2" tmp line
  grep -q "^${key}=$" "$OUT" || return 0
  tmp="$(mktemp)"
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$line" = "${key}=" ]; then
      printf '%s=%s\n' "$key" "$value"
    else
      printf '%s\n' "$line"
    fi
  done < "$OUT" > "$tmp"
  cat "$tmp" > "$OUT"   # overwrite content, preserve $OUT's existing 0600 mode
  rm -f "$tmp"
}

# Read the current value of a key from $OUT (empty if unset).
get_val() { grep -E "^$1=" "$OUT" | head -1 | cut -d'=' -f2-; }

set_if_blank "LITELLM_MASTER_KEY" "sk-$(rand_alnum 28)"
set_if_blank "POSTGRES_PASSWORD"  "$(rand_alnum 28)"
set_if_blank "LITELLM_UI_PASSWORD" "$(rand_alnum 24)"
set_if_blank "WEBUI_SECRET_KEY" "$(rand_alnum 32)"
# Derived (depend on the keys set above):
set_if_blank "DATABASE_URL" "postgresql://$(get_val POSTGRES_USER):$(get_val POSTGRES_PASSWORD)@litellm-db:5432/$(get_val POSTGRES_DB)"
set_if_blank "OPENAI_API_KEY" "$(get_val LITELLM_MASTER_KEY)"   # Open WebUI reads the key under this name

# Open WebUI gets a least-privilege secrets file with only the two keys it needs
# (so the third-party image never sees POSTGRES_PASSWORD/HF_TOKEN/master key).
WEBUI_OUT="secrets.webui.env"
{
  echo "# GENERATED by gen-secrets.sh — least-privilege secrets for Open WebUI. DO NOT EDIT."
  echo "OPENAI_API_KEY=$(get_val OPENAI_API_KEY)"
  echo "WEBUI_SECRET_KEY=$(get_val WEBUI_SECRET_KEY)"
} > "$WEBUI_OUT"
chmod 600 "$WEBUI_OUT"

# litellm-db gets only the POSTGRES_* it needs (the stock postgres image must
# never see HF_TOKEN / REGISTRY_TOKEN / the master key).
DB_OUT="secrets.db.env"
{
  echo "# GENERATED by gen-secrets.sh — least-privilege secrets for litellm-db. DO NOT EDIT."
  echo "POSTGRES_DB=$(get_val POSTGRES_DB)"
  echo "POSTGRES_USER=$(get_val POSTGRES_USER)"
  echo "POSTGRES_PASSWORD=$(get_val POSTGRES_PASSWORD)"
} > "$DB_OUT"
chmod 600 "$DB_OUT"

# litellm runtime gets auth/UI/DB-URL only — not HF_TOKEN / REGISTRY_TOKEN.
LITELLM_OUT="secrets.litellm.env"
{
  echo "# GENERATED by gen-secrets.sh — least-privilege secrets for litellm. DO NOT EDIT."
  echo "LITELLM_MASTER_KEY=$(get_val LITELLM_MASTER_KEY)"
  echo "LITELLM_UI_USERNAME=$(get_val LITELLM_UI_USERNAME)"
  echo "LITELLM_UI_PASSWORD=$(get_val LITELLM_UI_PASSWORD)"
  echo "DATABASE_URL=$(get_val DATABASE_URL)"
} > "$LITELLM_OUT"
chmod 600 "$LITELLM_OUT"

echo "secrets.env ready (mode 600). Fill in HF_TOKEN (for make download). Projected: secrets.webui.env, secrets.db.env, secrets.litellm.env."
